---
title: "Pred1Project_code"
author: "Rachel Rosenberg"
date: "11/12/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r}
setwd("~/Predictive_1/Pred1Project")
book <- read.csv("book.csv", sep = ',', stringsAsFactors = F)
booktest <- read.csv("booktest.csv", sep = ',', stringsAsFactors = F)
booktrain <- read.csv("booktrain.csv", sep = ',', stringsAsFactors = F)
ordersall <- read.csv("ordersall.csv", sep = ',', stringsAsFactors = F)
```

## Manipulate data

```{r}
## Join tables
# booktrain, ordersall, book - on customerID
cust_db <- merge(booktrain, book, by.x = "id", by.y = "id")
cust_db <- merge(cust_db, ordersall, by.x = "id", by.y = "id")
head(cust_db)

## Weight recent purchases
# Use a loop - build function to weight
# Have to use ordersall 
weight_recent <- function(cust_db){
        for(i in 1:nrow(cust_db)){
                date <- as.Date(cust_db$orddate[i], format = "%d-%b-%y")
                if (date >= as.Date("2013-01-01")){
                        cust_db$wgtprice[i] <- 1.6 * cust_db$price[i]
                }
                else if (date < as.Date("2013-01-01") & date > as.Date("2012-01-01")){
                        cust_db$wgtprice[i] <- 1.4 * cust_db$price[i]
                }
                else if (date < as.Date("2012-01-01") & date > as.Date("2011-01-01")){
                        cust_db$wgtprice[i] <- 1.2 * cust_db$price[i]
                }
                else if (date < as.Date("2011-01-01") & date > as.Date("2010-01-01")){
                        cust_db$wgtprice[i] <- 1.1 * cust_db$price[i]
                }
        }
  return(cust_db)
}

cust_db <- weight_recent(cust_db)
## 
```

## Make a binary column - did the customer purchase a book in response to the promo?

```{r}
cust_db_binom <- cust_db # copy cust_db to a new db for manipulation

last_three_months <- function(cust_db_binom){
        for(i in 1:nrow(cust_db_binom)){
                if (cust_db_binom$logtargamt.x[i] > 0){
                        cust_db_binom$logtargamt.x[i] <- 1
                }
        }
        return(cust_db_binom)
}

cust_db_binom <- last_three_months(cust_db_binom)

# get rid of extraneous columns in dataframe
keeps <- c("orddate", "ordnum", "category", "qty","price", "tof", "amount","frequency","recency","logtargamt.x","id")
cust_db_binom <- cust_db_binom[keeps]
```

## Fit logarithmic model - did customer respond to promo?

```{r}

fit <- glm(logtargamt.x ~ recency  + factor(category) + amount + frequency, data = cust_db_binom, family = binomial)
summary(fit)
plot(fit)

cust_db_binom$prediction <- predict(fit, cust_db_binom, type = "response")

```

## Remove customers who did not respond to promo

```{r}
cust_db_
```

## Fit multiple linear regression model

```{r}

```


```{r}
cust_db_binom <- cust_db # copy cust_db to a new db for manipulation

last_three_months <- function(cust_db_binom){
        for(i in 1:nrow(cust_db_binom)){
                if (cust_db_binom$logtargamt.x[i] > 0){
                        cust_db_binom$logtargamt.x[i] <- 1
                }
        }
        return(cust_db_binom)
}

cust_db_binom <- last_three_months(cust_db_binom)

# get rid of extraneous columns in dataframe
keeps <- c("orddate", "ordnum", "category", "qty","price", "tof", "amount","frequency","recency","logtargamt.x","id")
cust_db_binom <- cust_db_binom[keeps]
```



## Fit logarithmic model without merging the orders table- did customer respond to promo?

```{r}
library(nnet)
book <- book[book$amount < 1000,] #filter out huge purchasers 

cust_db_binom <- merge(booktrain, book, by.x = "id", by.y = "id") #merge training data onto book dataset

#add variable for amount weighted by most recent purchase
cust_db_binom$wgtamount <- cust_db_binom$amount / (cust_db_binom$recency + 1)

#convert the logtargamt to binomial
for(i in 1:nrow(cust_db_binom)){
                if (cust_db_binom$logtargamt.x[i] > 0){
                        cust_db_binom$logtargamt.x[i] <- 1
                }
        }

fit <- glm(logtargamt.x ~ recency + wgtamount, data = cust_db_binom, family = binomial)


summary(fit)
plot(fit)
plot(fit$residuals)

cust_db_binom$prediction <- predict(fit, cust_db_binom, type = "response") #convert odds to prediction

tab = table(cust_db_binom$logtargamt.x, cust_db_binom$prediction > .04) #create confusion matrix
tab

mean(cust_db_binom[cust_db_binom$logtargamt.x == 1,]$prediction) #mean predictions given actual binomial
mean(cust_db_binom[cust_db_binom$logtargamt.x == 0,]$prediction)

```

